# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0010_ipaddress_help_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('protocol', models.PositiveSmallIntegerField(choices=[(0, b'TCP'), (1, b'UDP')], default=0)),
                ('port', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ports', to='ipam.IPAddress', verbose_name=b'ip_address')),
            ],
            options={
                'ordering': ['ip_address', 'port'],
                'verbose_name': 'Service Port',
                'verbose_name_plural': 'Service Ports',
            },
        ),
        migrations.AlterUniqueTogether(
            name='serviceport',
            unique_together={('ip_address', 'port', 'protocol')},
        ),
    ]
