# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0013_prefix_add_is_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlan',
            options={'ordering': ['site', 'group', 'vid', 'service_identifier'], 'verbose_name': 'VLAN', 'verbose_name_plural': 'VLANs'},
        ),
        migrations.AddField(
            model_name='vlan',
            name='service_identifier',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16777215)], verbose_name=b'Service Identifier'),
        ),
    ]
