# Generated by Django 2.2.1 on 2019-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0024_vrf_allow_null_rd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vlangroup',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('group', 'vid'), name='unique_group_and_vid_on_vlan'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_group_and_name_on_vlan'),
        ),
        migrations.AddConstraint(
            model_name='vlangroup',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_site_and_name_on_vlangroup'),
        ),
        migrations.AddConstraint(
            model_name='vlangroup',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_site_and_slug_on_vlangroup'),
        ),
    ]
