# Generated by Django 2.2.4 on 2019-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0027_ipaddress_add_dns_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vlangroup',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('group', 'vid'), name='vlan_group_vid_key'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='vlan_group_name_key'),
        ),
        migrations.AddConstraint(
            model_name='vlangroup',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='vlangroup_site_name_key'),
        ),
        migrations.AddConstraint(
            model_name='vlangroup',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='vlangroup_site_slug_key'),
        ),
    ]
