# Generated by Django 4.1.9 on 2023-07-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0092_delete_jobresult'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ipam', '0067_ipaddressfunction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPAddressFunction',
            new_name='IPAddressFunctionAssignments',
        ),
        migrations.AlterModelOptions(
            name='ipaddressfunctionassignments',
            options={'ordering': ('function',), 'verbose_name': 'IP Address Function Assignments'},
        ),
    ]
