# Generated by Django 5.2.5 on 2025-11-25 06:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0085_alter_prefix_parent'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='prefix',
            name='ipam_prefix_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='prefix',
            name='ipam_prefix_insert',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prefix',
            trigger=pgtrigger.compiler.Trigger(
                name='ipam_prefix_delete',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n-- Update Child Prefix's with Prefix's PARENT  This is a safe assumption based on the fact that the parent would be the\n-- next direct parent for anything else that could contain this prefix\nUPDATE ipam_prefix SET parent_id=OLD.parent_id WHERE parent_id=OLD.id;\nRETURN OLD;\n",  # noqa: E501
                    hash='ee3f890009c05a3617428158e7b6f3d77317885d',
                    operation='DELETE',
                    pgid='pgtrigger_ipam_prefix_delete_e7810',
                    table='ipam_prefix',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prefix',
            trigger=pgtrigger.compiler.Trigger(
                name='ipam_prefix_insert',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n-- Update the prefix with the new parent if the parent is the most appropriate prefix\nUPDATE ipam_prefix\nSET parent_id=NEW.id\nWHERE\n    prefix << NEW.prefix\n    AND\n    (\n        (vrf_id = NEW.vrf_id OR (vrf_id IS NULL AND NEW.vrf_id IS NULL))\n        OR\n        (\n            NEW.vrf_id IS NULL\n            AND\n            NEW.status = 'container'\n            AND\n            NOT EXISTS(\n                SELECT 1 FROM ipam_prefix p WHERE p.prefix >> ipam_prefix.prefix AND p.vrf_id = ipam_prefix.vrf_id\n            )\n        )\n    )\n    AND id != NEW.id\n    AND NOT EXISTS (\n        SELECT 1 FROM ipam_prefix p\n        WHERE\n            p.prefix >> ipam_prefix.prefix\n            AND p.prefix << NEW.prefix\n            AND (\n                (p.vrf_id = ipam_prefix.vrf_id OR (p.vrf_id IS NULL AND ipam_prefix.vrf_id IS NULL))\n                OR\n                (p.vrf_id IS NULL AND p.status = 'container')\n            )\n            AND p.id != NEW.id\n    )\n;\nRETURN NEW;\n",  # noqa: E501
                    hash='1d71498f09e767183d3b0d29c06c9ac9e2cc000a',
                    operation='INSERT',
                    pgid='pgtrigger_ipam_prefix_insert_46c72',
                    table='ipam_prefix',
                    when='AFTER',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prefix',
            trigger=pgtrigger.compiler.Trigger(
                name='ipam_prefix_update',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n-- When a prefix changes, reassign any IPAddresses that no longer\n-- fall within the new prefix range to the parent prefix (or set null if no parent exists)\nUPDATE ipam_prefix\nSET parent_id = OLD.parent_id\nWHERE\n    parent_id = NEW.id\n    -- IP address no longer contained within the updated prefix\n    AND NOT (prefix << NEW.prefix);\n\n-- Update the prefix with the new parent if the parent is the most appropriate prefix\nUPDATE ipam_prefix\nSET parent_id=NEW.id\nWHERE\n    prefix << NEW.prefix\n    AND\n    (\n        (vrf_id = NEW.vrf_id OR (vrf_id IS NULL AND NEW.vrf_id IS NULL))\n        OR\n        (\n            NEW.vrf_id IS NULL\n            AND\n            NEW.status = 'container'\n            AND\n            NOT EXISTS(\n                SELECT 1 FROM ipam_prefix p WHERE p.prefix >> ipam_prefix.prefix AND p.vrf_id = ipam_prefix.vrf_id\n            )\n        )\n    )\n    AND id != NEW.id\n    AND NOT EXISTS (\n        SELECT 1 FROM ipam_prefix p\n        WHERE\n            p.prefix >> ipam_prefix.prefix\n            AND p.prefix << NEW.prefix\n            AND (\n                (p.vrf_id = ipam_prefix.vrf_id OR (p.vrf_id IS NULL AND ipam_prefix.vrf_id IS NULL))\n                OR\n                (p.vrf_id IS NULL AND p.status = 'container')\n            )\n            AND p.id != NEW.id\n    )\n;\nRETURN NEW;\n",  # noqa: E501
                    hash='747230a84703df5a4aa3d32e7f45b5a32525b799',
                    operation='UPDATE',
                    pgid='pgtrigger_ipam_prefix_update_e5fca',
                    table='ipam_prefix',
                    when='AFTER',
                ),
            ),
        ),
    ]
