# Generated by Django 5.0.9 on 2025-02-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0086_gfk_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='ipam.prefix',
            ),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='prefix',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ip_addresses',
                to='ipam.prefix',
            ),
        ),
        migrations.AddField(
            model_name='iprange',
            name='prefix',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ip_ranges',
                to='ipam.prefix',
            ),
        ),
        migrations.AddField(
            model_name='prefix',
            name='aggregate',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='prefixes',
                to='ipam.aggregate',
            ),
        ),
    ]
