# Generated by Django 5.2.5 on 2025-11-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0089_prefix_ipam_prefix_delete_prefix_ipam_prefix_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='children',
                to='ipam.prefix',
            ),
        ),
    ]
