# Generated by Django 6.0.6 on 2026-07-15 17:08

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import netbox.models.deletion


def copy_port_mappings(apps, schema_editor):
    """
    Copy the (protocol, ports) data previously stored directly on each Service/ServiceTemplate into a
    single child port mapping row.
    """
    Service = apps.get_model('ipam', 'Service')
    ServiceTemplate = apps.get_model('ipam', 'ServiceTemplate')
    ServicePortMapping = apps.get_model('ipam', 'ServicePortMapping')
    ServiceTemplatePortMapping = apps.get_model('ipam', 'ServiceTemplatePortMapping')

    ServicePortMapping.objects.bulk_create(
        [
            ServicePortMapping(service_id=service.pk, protocol=service.protocol, ports=service.ports)
            for service in Service.objects.all()
            if service.ports
        ],
        batch_size=1000,
    )
    ServiceTemplatePortMapping.objects.bulk_create(
        [
            ServiceTemplatePortMapping(
                service_template_id=template.pk, protocol=template.protocol, ports=template.ports
            )
            for template in ServiceTemplate.objects.all()
            if template.ports
        ],
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0141_custom_field_nulls_first"),
        ("ipam", "0093_denormalization_triggers"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        # Create the new child models (without the parent FK, which is added below)
        migrations.CreateModel(
            name="ServicePortMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("protocol", models.CharField(max_length=50)),
                (
                    "ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(65535),
                            ]
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "service port mapping",
                "verbose_name_plural": "service port mappings",
                "ordering": ("protocol",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceTemplatePortMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("protocol", models.CharField(max_length=50)),
                (
                    "ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(65535),
                            ]
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "service template port mapping",
                "verbose_name_plural": "service template port mappings",
                "ordering": ("protocol",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="serviceportmapping",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_mappings",
                to="ipam.service",
            ),
        ),
        migrations.AddField(
            model_name="servicetemplateportmapping",
            name="service_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_mappings",
                to="ipam.servicetemplate",
            ),
        ),

        # Migrate existing data into the child tables before dropping the old columns. This migration
        # is effectively forward-only: reversing it re-adds the non-nullable protocol/ports columns with
        # no default, which fails on a populated table (the RunPython reverse is a no-op regardless).
        migrations.RunPython(copy_port_mappings, migrations.RunPython.noop),

        # Drop the protocol/ports data from the parent models
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ("name", "id")},
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="ipam_servic_protoco_e2901d_idx",
        ),
        migrations.RemoveField(
            model_name="servicetemplate",
            name="_ports_lowest",
        ),
        migrations.RemoveField(
            model_name="servicetemplate",
            name="ports",
        ),
        migrations.RemoveField(
            model_name="servicetemplate",
            name="protocol",
        ),
        migrations.RemoveField(
            model_name="service",
            name="_ports_lowest",
        ),
        migrations.RemoveField(
            model_name="service",
            name="ports",
        ),
        migrations.RemoveField(
            model_name="service",
            name="protocol",
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["name", "id"], name="ipam_servic_name_b3260b_idx"
            ),
        ),

        # Enforce one mapping row per protocol per parent
        migrations.AddConstraint(
            model_name="serviceportmapping",
            constraint=models.UniqueConstraint(
                fields=("service", "protocol"),
                name="ipam_serviceportmapping_unique_service_protocol",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetemplateportmapping",
            constraint=models.UniqueConstraint(
                fields=("service_template", "protocol"),
                name="ipam_servicetemplateportmapping_unique_servicetemplate_protocol",
            ),
        ),
    ]
