# Generated by Django 6.0.6 on 2026-07-16 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


def populate_port_mappings(apps, schema_editor):
    """
    Build the new ``port_mappings`` array (e.g. ['tcp/80', 'tcp/443']) from the legacy protocol/ports
    fields on each Service/ServiceTemplate. Processed in batches to bound memory on large installs.
    """
    for model_name in ('Service', 'ServiceTemplate'):
        model = apps.get_model('ipam', model_name)
        batch = []
        for obj in model.objects.filter(ports__len__gt=0).iterator(chunk_size=1000):
            # dict.fromkeys dedupes while preserving order (legacy ports weren't guaranteed unique),
            # so a duplicated port doesn't produce a duplicate mapping that later fails validation.
            obj.port_mappings = list(dict.fromkeys(f'{obj.protocol}/{port}' for port in obj.ports))
            batch.append(obj)
            if len(batch) >= 1000:
                model.objects.bulk_update(batch, ['port_mappings'])
                batch = []
        if batch:
            model.objects.bulk_update(batch, ['port_mappings'])


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0141_custom_field_nulls_first"),
        ("ipam", "0093_denormalization_triggers"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        # Add the new field to both models first
        migrations.AddField(
            model_name="service",
            name="port_mappings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=63), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="servicetemplate",
            name="port_mappings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=63), blank=True, default=list
            ),
        ),
        # Migrate existing protocol/ports data into port_mappings before dropping the old fields. This
        # migration is effectively forward-only: reversing it re-adds the non-nullable protocol/ports
        # columns with no default, which fails on a populated table (the RunPython reverse is a no-op).
        migrations.RunPython(populate_port_mappings, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ("name", "id")},
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="ipam_servic_protoco_e2901d_idx",
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["name", "id"], name="ipam_servic_name_b3260b_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="servicetemplate",
            name="_ports_lowest",
        ),
        migrations.RemoveField(
            model_name="servicetemplate",
            name="ports",
        ),
        migrations.RemoveField(
            model_name="servicetemplate",
            name="protocol",
        ),
        migrations.RemoveField(
            model_name="service",
            name="_ports_lowest",
        ),
        migrations.RemoveField(
            model_name="service",
            name="ports",
        ),
        migrations.RemoveField(
            model_name="service",
            name="protocol",
        ),
    ]
