# Generated by Django 6.0.6 on 2026-07-01 21:08

from django.db import migrations, models


def populate_port_assignments(apps, schema_editor):
    """
    Populate port_assignments from the legacy protocol and ports fields.
    """
    for model_name in ('Service', 'ServiceTemplate'):
        model = apps.get_model('ipam', model_name)
        for obj in model.objects.all().iterator():
            obj.port_assignments = [
                {'protocol': obj.protocol, 'port': port}
                for port in (obj.ports or [])
            ]
            obj.save(update_fields=['port_assignments'])


def restore_protocol_ports(apps, schema_editor):
    """
    Reverse: reconstruct the legacy protocol and ports fields from port_assignments. This is lossy
    for services which mix protocols (only the first assignment's protocol is retained).
    """
    for model_name in ('Service', 'ServiceTemplate'):
        model = apps.get_model('ipam', model_name)
        for obj in model.objects.all().iterator():
            assignments = obj.port_assignments or []
            obj.protocol = assignments[0]['protocol'] if assignments else ''
            obj.ports = sorted({assignment['port'] for assignment in assignments})
            obj.save(update_fields=['protocol', 'ports'])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0140_imageattachment_image_size'),
        ('ipam', '0093_denormalization_triggers'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        # Add the new field to both models
        migrations.AddField(
            model_name='service',
            name='port_assignments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='port_assignments',
            field=models.JSONField(blank=True, default=list),
        ),
        # Copy existing protocol/ports data into port_assignments
        migrations.RunPython(populate_port_assignments, restore_protocol_ports),
        # Remove the legacy protocol/ports fields and their index
        migrations.RemoveIndex(
            model_name='service',
            name='ipam_servic_protoco_e2901d_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='servicetemplate',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='servicetemplate',
            name='ports',
        ),
        # Update ordering and index to reflect the removal of protocol
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['_ports_lowest', 'id'], name='ipam_servic__ports__10a2cc_idx'),
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('_ports_lowest', 'id')},
        ),
    ]
