# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0096_ipaddress_host_index'),
        ('ipam', '0095_multi_protocol_services'),
    ]

    operations = [
    ]
