# Generated by Django 3.2.12 on 2022-03-15 13:08

from django.db import migrations
import django_better_admin_arrayfield.models.fields
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allowed_ips',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=ipam.fields.IPNetworkField(), blank=True, null=True, size=None),
        ),
    ]
