# Generated by Django 3.2.12 on 2022-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allowed_ipranges',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
