# Generated by Django 4.2.2 on 2023-07-06 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_netboxgroup_netboxuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[],
            options={
                'verbose_name': 'Token',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.token',),
        ),
    ]
