# Generated by Django 4.1.9 on 2023-06-02 16:55

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_token_allowed_ips_last_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBoxUser',
            fields=[],
            options={
                'verbose_name': 'User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
