# Generated by Django 4.2.6 on 2023-11-07 21:49

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0011_contactassignment_tags'),
        ('extras', '0099_cachedvalue_ordering'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ipam', '0067_ipaddress_index_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSecProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protocol', models.CharField()),
                ('ike_version', models.PositiveSmallIntegerField(default=2)),
                ('phase1_encryption', models.CharField()),
                ('phase1_authentication', models.CharField()),
                ('phase1_group', models.PositiveSmallIntegerField()),
                ('phase1_sa_lifetime', models.PositiveIntegerField(blank=True, null=True)),
                ('phase2_encryption', models.CharField()),
                ('phase2_authentication', models.CharField()),
                ('phase2_group', models.PositiveSmallIntegerField()),
                ('phase2_sa_lifetime', models.PositiveIntegerField(blank=True, null=True)),
                ('phase2_sa_lifetime_data', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'tunnel',
                'verbose_name_plural': 'tunnels',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('encapsulation', models.CharField(max_length=50)),
                ('preshared_key', models.TextField(blank=True)),
                ('tunnel_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ipsec_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tunnels', to='vpn.ipsecprofile')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tunnels', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'tunnel',
                'verbose_name_plural': 'tunnels',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TunnelTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('role', models.CharField(default='peer', max_length=50)),
                ('interface_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('interface_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('outside_ip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tunnel_termination', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='vpn.tunnel')),
            ],
            options={
                'verbose_name': 'tunnel termination',
                'verbose_name_plural': 'tunnel terminations',
                'ordering': ('tunnel', 'pk'),
            },
        ),
    ]
