# Generated by Django 4.2.6 on 2023-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsecprofile',
            name='phase1_sa_lifetime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipsecprofile',
            name='phase2_sa_lifetime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
