# Generated by Django 4.2.6 on 2023-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_alter_ipsecprofile_phase1_sa_lifetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='tunnel_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
