# Generated by Django 4.1.5 on 2023-01-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='git_branch',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='username',
        ),
        migrations.AddField(
            model_name='datasource',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
