# Generated by Django 4.1.5 on 2023-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_synced',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
