# Generated by Django 4.1.5 on 2023-01-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datasource_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
