# Generated by Django 4.1.5 on 2023-01-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datasource_created_datasource_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='status',
            field=models.CharField(default='new', editable=False, max_length=50),
        ),
    ]
