# Generated by Django 4.1.5 on 2023-02-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datasource_custom_field_data_datasource_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
