# Generated by Django 5.0.1 on 2024-01-26 18:11

from django.db import migrations


def migrate_report_jobs(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Job = apps.get_model('core', 'Job')

    # Delete the new ContentType effected by the introduction of core.ConfigRevision
    report_content_type = ContentType.objects.get(app_label='extras', model='reportmodule')
    script_content_type = ContentType.objects.get(app_label='extras', model='scriptmodule')
    jobs = Job.objects.filter(object_type_id=report_content_type.id).update(object_type_id=script_content_type.id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gfk_indexes'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_report_jobs,
            reverse_code=migrations.RunPython.noop
        ),
    ]
