# Generated by Django 5.2.5 on 2025-09-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_redundant_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configrevision',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='configrevision',
            constraint=models.UniqueConstraint(
                condition=models.Q(('actvive', True)), fields=('active',), name='unique_active_config_revision'
            ),
        ),
    ]
