# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0006_auto_20160908_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='commit_rate',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='port_speed',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='pp_info',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='site',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='upstream_speed',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='xconnect_id',
        ),
    ]
