# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0007_auto_20160908_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termination',
            name='comments',
        ),
    ]
