# Generated by Django 2.2.8 on 2020-01-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0007_circuit_add_description_squashed_0017_circuittype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='circuittermination',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='circuittype',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
