# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0008_remove_termination_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='termination',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
