# Generated by Django 2.2.1 on 2019-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0014_circuittermination_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circuit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='circuittermination',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='circuit',
            constraint=models.UniqueConstraint(fields=('provider', 'cid'), name='unique_provider_and_cid'),
        ),
        migrations.AddConstraint(
            model_name='circuittermination',
            constraint=models.UniqueConstraint(fields=('circuit', 'term_side'), name='unique_circuit_and_termside'),
        ),
    ]
