# Generated by Django 2.2.4 on 2019-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0015_custom_tag_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circuit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='circuittermination',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='circuit',
            constraint=models.UniqueConstraint(fields=('provider', 'cid'), name='circuit_provider_cid_key'),
        ),
        migrations.AddConstraint(
            model_name='circuittermination',
            constraint=models.UniqueConstraint(fields=('circuit', 'term_side'), name='circuittermination_circuit_termside_key'),
        ),
    ]
