# Generated by Django 2.2.5 on 2019-10-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0016_generic_connected_endpoint'),
        ('dcim', '0077_migrate_connected_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuittermination',
            name='old_connected_endpoint',
        ),
    ]
