# Generated by Django 4.0.5 on 2022-09-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0161_cabling_cleanup'),
        ('circuits', '0038_cabling_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuittermination',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circuit_terminations', to='dcim.location'),
        ),
    ]
