# Generated by Django 4.1.9 on 2023-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0042_provideraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuittermination',
            name='termination_type',
            field=models.CharField(default='site', max_length=50),
        ),
    ]
