# Generated by Django 5.0.7 on 2024-07-19 04:18

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0043_circuittype_color'),
        ('extras', '0118_notifications'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='circuitgroups',
                        to='tenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Circuit group',
                'verbose_name_plural': 'Circuit group',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CircuitGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ('priority', models.CharField(blank=True, max_length=50)),
                (
                    'circuit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='circuit_group_assignments',
                        to='circuits.circuit',
                    ),
                ),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.circuitgroup')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Circuit group assignment',
                'verbose_name_plural': 'Circuit group assignments',
                'ordering': ('circuit', 'priority', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='circuitgroup',
            name='circuits',
            field=models.ManyToManyField(through='circuits.CircuitGroupAssignment', to='circuits.circuit'),
        ),
        migrations.AddConstraint(
            model_name='circuitgroupassignment',
            constraint=models.UniqueConstraint(
                fields=('circuit', 'group'), name='circuits_circuitgroupassignment_unique_circuit_assignment'
            ),
        ),
    ]
