# Generated by Django 6.1.1 on 2026-10-02 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0060_denormalization_triggers'),
        ('dcim', '0251_fix_ltree_cascade_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuittermination',
            name='_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_terminations', to='dcim.region'),
        ),
        migrations.AlterField(
            model_name='circuittermination',
            name='_site_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_terminations', to='dcim.sitegroup'),
        ),
    ]
