# Generated by Django 3.1.3 on 2021-04-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0019_standardize_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
