# Generated by Django 4.1.8 on 2023-05-16 21:20

from django.db import migrations
import utilities.fields
from django.db.models import Count


def populate_virtualmachine_counts(apps, schema_editor):
    VirtualMachine = apps.get_model('virtualization', 'VirtualMachine')

    vms = list(VirtualMachine.objects.annotate(interface_count=Count('interfaces', distinct=True)))

    for vm in vms:
        vm._interface_count = vm.interface_count

    VirtualMachine.objects.bulk_update(vms, ['_interface_count'])


class Migration(migrations.Migration):
    dependencies = [
        ('virtualization', '0034_standardize_description_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='_interface_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.RunPython(
            code=populate_virtualmachine_counts,
            reverse_code=migrations.RunPython.noop
        ),
    ]
