# Generated by Django 5.0.7 on 2024-07-31 05:40

from django.db import migrations
from django.db.models import F


def convert_disk_size(apps, schema_editor):
    VirtualDisk = apps.get_model('virtualization', 'VirtualDisk')
    VirtualDisk.objects.filter(disk__isnull=False).update(disk=F('size') * 1000)


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0040_virtualmachine_serial_number'),
    ]

    operations = [
        migrations.RunPython(
            code=convert_disk_size,
            reverse_code=migrations.RunPython.noop
        ),
    ]
