# Generated by Django 5.0.7 on 2024-07-31 05:40

from django.db import migrations
from django.db.models import F


def convert_disk_size(apps, schema_editor):
    VirtualDisk = apps.get_model('virtualization', 'VirtualDisk')
    VirtualDisk.objects.filter(size__isnull=False).update(size=F('size') * 1000)

    # Need to save all Vms to recalc disk size
    id_list = VirtualDisk.objects.values_list('virtual_machine_id').distinct()
    VirtualMachine = apps.get_model('virtualization', 'VirtualMachine')
    vms = VirtualMachine.objects.filter(id__in=id_list)
    for vm in vms:
        vm.disk = self.virtualdisks.aggregate(Sum('size', default=0))['size__sum']
        vm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0040_virtualmachine_serial_number'),
    ]

    operations = [
        migrations.RunPython(
            code=convert_disk_size,
            reverse_code=migrations.RunPython.noop
        ),
    ]
