# Generated by Django 5.1.2 on 2024-10-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0041_charfield_null_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vminterface',
            old_name='mac_address',
            new_name='_mac_address',
        ),
    ]
