# Generated by Django 5.1.2 on 2024-10-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0043_rename_mac_address_vminterface__mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vminterface',
            name='_mac_address',
        ),
    ]
