# Generated by Django 5.2.7 on 2025-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0050_virtualmachine_start_on_boot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='start_on_boot',
            field=models.CharField(blank=True, default='off', max_length=32, null=True),
        ),
    ]
