# Generated by Django 5.2.11 on 2026-04-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0054_virtualmachinetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ('name', 'pk'), 'permissions': [('render_config', 'Render VM configuration')]},
        ),
    ]
