# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_auto_20160706_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
