# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0025_devicetype_add_interface_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['site', 'name', 'group']},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together=set([('site', 'facility_id'), ('site', 'name', 'group')]),
        ),
    ]
