# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0049_rackreservation_change_user'),
        ('dcim', '0050_rackreservation_tenant'),
    ]

    operations = [
    ]
