# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0055_virtualchassis_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='napalm_port',
            field=models.PositiveIntegerField(blank=True, help_text='The port to be used by NAPALM driver when interacting with devices', null=True, verbose_name='NAPALM port'),
        ),
        migrations.AddField(
            model_name='platform',
            name='napalm_transport',
            field=models.CharField(blank=True, help_text='The transport protocol to be used by NAPALM driver when interacting with devices', max_length=50, verbose_name='NAPALM transport type'),
        ),
    ]
