# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0055_virtualchassis_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='is_rack_furniture',
            field=models.BooleanField(default=False, help_text='This type of device is for rack furniture such as shelves or blanks', verbose_name='Is rack furniture'),
        ),
    ]
