# Generated by Django 2.2.1 on 2019-05-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_deprecate_nullablecharfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='termination_a_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['consoleport', 'consoleserverport', 'interface', 'poweroutlet', 'powerport', 'frontport', 'rearport', 'circuittermination']}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='termination_b_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['consoleport', 'consoleserverport', 'interface', 'poweroutlet', 'powerport', 'frontport', 'rearport', 'circuittermination']}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='cable',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consoleport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consoleporttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consoleserverport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consoleserverporttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='devicebay',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='devicebaytemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='frontport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='frontporttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='interfacetemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='poweroutlet',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='poweroutlettemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='powerport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='powerporttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rackgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rearport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rearporttemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cable',
            constraint=models.UniqueConstraint(fields=('termination_a_type', 'termination_a_id'), name='unique_terminations_a_to_b_on_cable'),
        ),
        migrations.AddConstraint(
            model_name='cable',
            constraint=models.UniqueConstraint(fields=('termination_b_type', 'termination_b_id'), name='unique_terminations_b_to_a_on_cable'),
        ),
        migrations.AddConstraint(
            model_name='consoleport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_consoleport'),
        ),
        migrations.AddConstraint(
            model_name='consoleporttemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_consoleporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='consoleserverport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_consoleserverport'),
        ),
        migrations.AddConstraint(
            model_name='consoleserverporttemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_consoleserverporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('rack', 'position', 'face'), name='unique_rack_and_position_and_face_on_device'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('virtual_chassis', 'vc_position'), name='unique_virtualchassis_and_vcpos_on_device'),
        ),
        migrations.AddConstraint(
            model_name='devicebay',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_devicebay'),
        ),
        migrations.AddConstraint(
            model_name='devicebaytemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_devicebaytemplate'),
        ),
        migrations.AddConstraint(
            model_name='devicetype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model'), name='unique_manufacturer_and_model_on_devicetype'),
        ),
        migrations.AddConstraint(
            model_name='devicetype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'slug'), name='unique_manufacturer_and_slug_on_devicetype'),
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_frontport'),
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('rear_port', 'rear_port_position'), name='unique_rearport_and_rearportpos_on_frontport'),
        ),
        migrations.AddConstraint(
            model_name='frontporttemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_frontporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='frontporttemplate',
            constraint=models.UniqueConstraint(fields=('rear_port', 'rear_port_position'), name='unique_rearport_and_rearportpos_on_frontporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_interface'),
        ),
        migrations.AddConstraint(
            model_name='interfacetemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_interfacetemplate'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('device', 'parent', 'name'), name='unique_device_and_parent_and_name_on_inventoryitem'),
        ),
        migrations.AddConstraint(
            model_name='poweroutlet',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_poweroutlet'),
        ),
        migrations.AddConstraint(
            model_name='poweroutlettemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_poweroutlettemplate'),
        ),
        migrations.AddConstraint(
            model_name='powerport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_powerport'),
        ),
        migrations.AddConstraint(
            model_name='powerporttemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_powerporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_group_and_name_on_rack'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('group', 'facility_id'), name='unique_group_and_facility_on_rack'),
        ),
        migrations.AddConstraint(
            model_name='rackgroup',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_site_and_name_on_rackgroup'),
        ),
        migrations.AddConstraint(
            model_name='rackgroup',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_site_and_slug_on_rackgroup'),
        ),
        migrations.AddConstraint(
            model_name='rearport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_device_and_name_on_rearport'),
        ),
        migrations.AddConstraint(
            model_name='rearporttemplate',
            constraint=models.UniqueConstraint(fields=('device_type', 'name'), name='unique_devicetype_and_name_on_rearporttemplate'),
        ),
    ]
