# Generated by Django 2.2.2 on 2019-06-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_deprecate_nullablecharfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='_connected_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.Interface'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='_connected_circuittermination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='circuits.CircuitTermination'),
        ),
    ]
