# Generated by Django 2.2.2 on 2019-06-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0070_auto_20190612_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='_connected_circuittermination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.CircuitTermination'),
        ),
    ]
