# Generated by Django 2.2.5 on 2019-10-06 19:01

import django.db.models.deletion
from django.db import migrations, models


def connected_interface_to_endpoint(apps, schema_editor):
    Interface = apps.get_model('dcim', 'Interface')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    model_type = ContentType.objects.get_for_model(Interface)
    for interface in Interface.objects.exclude(_connected_interface=None):
        interface.connected_endpoint_type = model_type
        interface.connected_endpoint_id = interface._connected_interface.pk
        interface.save()


def connected_circuittermination_to_endpoint(apps, schema_editor):
    Interface = apps.get_model('dcim', 'Interface')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    CircuitTermination = apps.get_model('circuits', 'CircuitTermination')

    model_type = ContentType.objects.get_for_model(CircuitTermination)
    for interface in Interface.objects.exclude(_connected_circuittermination=None):
        interface.connected_endpoint_type = model_type
        interface.connected_endpoint_id = interface._connected_circuittermination.pk
        interface.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0075_cable_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='connected_endpoint_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='connected_endpoint_type',
            field=models.ForeignKey(blank=True, limit_choices_to={
                'model__in': ['consoleport', 'consoleserverport', 'interface', 'poweroutlet', 'powerport', 'frontport',
                              'rearport', 'circuittermination']
            }, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType'),
        ),

        migrations.RunPython(connected_interface_to_endpoint),
        migrations.RunPython(connected_circuittermination_to_endpoint),

        migrations.RemoveField(
            model_name='interface',
            name='_connected_circuittermination',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='_connected_interface',
        ),
    ]
