# Generated by Django 2.2.5 on 2019-10-06 19:01

from django.db import migrations


def connected_interface_to_endpoint(apps, schema_editor):
    interface_model = apps.get_model('dcim', 'Interface')
    contenttype_model = apps.get_model('contenttypes', 'ContentType')

    model_type = contenttype_model.objects.get_for_model(interface_model)
    for interface in interface_model.objects.exclude(_connected_interface=None):
        interface.connected_endpoint_type = model_type
        interface.connected_endpoint_id = interface._connected_interface.pk
        interface.save()


def connected_endpoint_to_interface(apps, schema_editor):
    interface_model = apps.get_model('dcim', 'Interface')
    contenttype_model = apps.get_model('contenttypes', 'ContentType')

    model_type = contenttype_model.objects.get_for_model(interface_model)
    for interface in interface_model.objects.filter(connected_endpoint_type=model_type):
        interface._connected_interface = interface.connected_endpoint
        interface.save()


def connected_circuittermination_to_endpoint(apps, schema_editor):
    interface_model = apps.get_model('dcim', 'Interface')
    contenttype_model = apps.get_model('contenttypes', 'ContentType')
    circuittermination_model = apps.get_model('circuits', 'CircuitTermination')

    model_type = contenttype_model.objects.get_for_model(circuittermination_model)
    for interface in interface_model.objects.exclude(_connected_circuittermination=None):
        interface.connected_endpoint_type = model_type
        interface.connected_endpoint_id = interface._connected_circuittermination.pk
        interface.save()


def connected_endpoint_to_circuittermination(apps, schema_editor):
    interface_model = apps.get_model('dcim', 'Interface')
    contenttype_model = apps.get_model('contenttypes', 'ContentType')
    circuittermination_model = apps.get_model('circuits', 'CircuitTermination')

    model_type = contenttype_model.objects.get_for_model(circuittermination_model)
    for interface in interface_model.objects.filter(connected_endpoint_type=model_type):
        interface._connected_circuittermination = interface.connected_endpoint
        interface.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0076_add_generic_connected_endpoint'),
    ]

    operations = [
        migrations.RunPython(connected_interface_to_endpoint,
                             connected_endpoint_to_interface),
        migrations.RunPython(connected_circuittermination_to_endpoint,
                             connected_endpoint_to_circuittermination),
    ]
