# Generated by Django 2.2.5 on 2019-10-06 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0077_migrate_connected_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='_connected_circuittermination',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='_connected_interface',
        ),
        migrations.RemoveField(
            model_name='consoleport',
            name='old_connected_endpoint',
        ),
    ]
