# Generated by Django 2.2.10 on 2020-03-27 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0099_powerfeed_negative_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.Site'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.Device'),
        ),
        migrations.CreateModel(
            name='InventoryItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('model', models.CharField(max_length=50)),
                ('part_number', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_types', to='dcim.Manufacturer')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.InventoryItemRole'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='dcim.InventoryItemType'),
        ),
    ]
