# Generated by Django 2.2.10 on 2020-03-31 19:43

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0038_webhook_template_support'),
        ('dcim', '0100_auto_20200327_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitemtype',
            options={'ordering': ['manufacturer', 'model']},
        ),
        migrations.AddField(
            model_name='inventoryitemtype',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='dcim.InventoryItemType'),
        ),
        migrations.AlterField(
            model_name='inventoryitemtype',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_item_types', to='dcim.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inventoryitemtype',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitemtype',
            unique_together={('manufacturer', 'slug'), ('manufacturer', 'model')},
        ),
    ]
