# Generated by Django 4.1.9 on 2023-06-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0066_iprange_mark_utilized'),
        ('dcim', '0172_larger_power_draw_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='oob_ip4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AddField(
            model_name='device',
            name='oob_ip6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
    ]
