# Generated by Django 4.1.9 on 2023-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0173_remove_napalm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='starting_unit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
