# Generated by Django 4.1.8 on 2023-05-16 20:18

from django.db import migrations
import utilities.fields


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0173_remove_napalm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='_console_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_console_server_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_device_bay_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_front_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_interface_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_inventory_item_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_power_outlet_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_power_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_rear_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
    ]
