# Generated by Django 4.2.2 on 2023-06-23 19:26

from django.db import migrations
import utilities.fields
from django.db.models import Count


def recalculate_device_counts(apps, schema_editor):
    Device = apps.get_model("dcim", "Device")
    devices = list(Device.objects.all().annotate(
        console_port_count=Count('consoleports', distinct=True),
        console_server_port_count=Count('consoleserverports', distinct=True),
        interface_count=Count('interfaces', distinct=True),
        front_port_count=Count('frontports', distinct=True),
        rear_port_count=Count('rearports', distinct=True),
        device_bay_count=Count('devicebays', distinct=True),
        inventory_item_count=Count('inventoryitems', distinct=True),
        power_port_count=Count('powerports', distinct=True),
        power_outlet_count=Count('poweroutlets', distinct=True),
    ))

    for device in devices:
        device._console_port_count = device.console_port_count
        device._console_server_port_count = device.console_server_port_count
        device._interface_count = device.interface_count
        device._front_port_count = device.front_port_count
        device._rear_port_count = device.rear_port_count
        device._device_bay_count = device.device_bay_count
        device._inventory_item_count = device.inventory_item_count
        device._power_port_count = device.power_port_count
        device._power_outlet_count = device.power_outlet_count

    Device.objects.bulk_update(
        devices,
        ['_console_port_count',
         '_console_server_port_count',
         '_interface_count',
         '_front_port_count',
         '_rear_port_count',
         '_device_bay_count',
         '_inventory_item_count',
         '_power_port_count',
         '_power_outlet_count'],
    )


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0174_rack_starting_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='_console_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_console_server_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_device_bay_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_front_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_interface_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_inventory_item_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_power_outlet_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_power_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='_rear_port_count',
            field=utilities.fields.CounterCacheField(default=0),
        ),
        migrations.RunPython(
            recalculate_device_counts,
            reverse_code=migrations.RunPython.noop
        ),
    ]
