# Generated by Django 4.2.2 on 2023-07-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0174_rack_starting_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetemplate',
            name='rf_role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
