# Generated by Django 4.1.10 on 2023-08-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0180_powerfeed_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_role',
            new_name='role',
        ),
    ]
