# Generated by Django 5.0.7 on 2024-07-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0189_moduletype_airflow_rack_airflow_racktype_airflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebay',
            name='module',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)ss',
                to='dcim.module',
            ),
        ),
        migrations.AddField(
            model_name='modulebaytemplate',
            name='module_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)ss',
                to='dcim.moduletype',
            ),
        ),
        migrations.AlterField(
            model_name='modulebaytemplate',
            name='device_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)ss',
                to='dcim.devicetype',
            ),
        ),
    ]
