# Generated by Django 5.1.2 on 2024-10-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0195_rename_mac_address_interface__mac_address_macaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='_mac_address',
        ),
    ]
