# Generated by Django 5.1.8 on 2025-04-17 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='tx_power',
            field=models.SmallIntegerField(blank=True, null=True, validators=[
                django.core.validators.MinValueValidator(-127), django.core.validators.MaxValueValidator(127)
            ]),
        ),
    ]
