# Generated by Django 5.2b1 on 2025-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0201_add_power_outlet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='outer_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racktype',
            name='outer_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
