import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0220_cable_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleport',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='consoleserverport',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='frontport',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='interface',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='powerfeed',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='poweroutlet',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='powerport',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
        migrations.AddField(
            model_name='rearport',
            name='cable_position',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1024),
                ],
            ),
        ),
    ]
