# Generated by Django 5.2.11 on 2026-03-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0230_interface_rf_channel_frequency_precision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name', 'pk'), 'permissions': [('render_config', 'Render configuration')]},
        ),
    ]
