# Generated by Django 6.0.6 on 2026-06-24 21:45

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import netbox.models.deletion
import utilities.fields
import utilities.json
import utilities.tracking


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0240_device__config_context_data"),
        ("extras", "0139_alter_customfieldchoiceset_extra_choices"),
        ("tenancy", "0025_ltree_paths"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="cooling_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="cooling_outlet_count",
            field=utilities.fields.CounterCacheField(
                default=0,
                editable=False,
                to_field="device",
                to_model="dcim.CoolingOutlet",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="cooling_port_count",
            field=utilities.fields.CounterCacheField(
                default=0,
                editable=False,
                to_field="device",
                to_model="dcim.CoolingPort",
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="cooling_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="cooling_outlet_template_count",
            field=utilities.fields.CounterCacheField(
                default=0,
                editable=False,
                to_field="device_type",
                to_model="dcim.CoolingOutletTemplate",
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="cooling_port_template_count",
            field=utilities.fields.CounterCacheField(
                default=0,
                editable=False,
                to_field="device_type",
                to_model="dcim.CoolingPortTemplate",
            ),
        ),
        migrations.AddField(
            model_name="moduletype",
            name="cooling_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="moduletype",
            name="cooling_outlet_template_count",
            field=utilities.fields.CounterCacheField(
                default=0,
                editable=False,
                to_field="module_type",
                to_model="dcim.CoolingOutletTemplate",
            ),
        ),
        migrations.AddField(
            model_name="moduletype",
            name="cooling_port_template_count",
            field=utilities.fields.CounterCacheField(
                default=0,
                editable=False,
                to_field="module_type",
                to_model="dcim.CoolingPortTemplate",
            ),
        ),
        migrations.AddField(
            model_name="rack",
            name="cooling_capability",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rack",
            name="cooling_capacity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="rack",
            name="has_rdhx",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="racktype",
            name="cooling_capability",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="racktype",
            name="cooling_capacity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.CreateModel(
            name="CoolingPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "diameter_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_diameter",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                ("name", models.CharField(db_collation="natural_sort", max_length=64)),
                ("label", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("cable_end", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "cable_connector",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
                (
                    "cable_positions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(1024),
                            ]
                        ),
                        blank=True,
                        null=True,
                    ),
                ),
                ("mark_connected", models.BooleanField(default=False)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "connector_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "maximum_flow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "heat_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.location",
                    ),
                ),
                (
                    "_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dcim.cablepath",
                    ),
                ),
                (
                    "_rack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.rack",
                    ),
                ),
                (
                    "_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.site",
                    ),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.cable",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.device",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.module",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "cooling port",
                "verbose_name_plural": "cooling ports",
                "ordering": ("device", "name"),
                "abstract": False,
            },
            bases=(
                netbox.models.deletion.DeleteMixin,
                models.Model,
                utilities.tracking.TrackingModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="CoolingOutlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "diameter_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_diameter",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                ("name", models.CharField(db_collation="natural_sort", max_length=64)),
                ("label", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("cable_end", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "cable_connector",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
                (
                    "cable_positions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(1024),
                            ]
                        ),
                        blank=True,
                        null=True,
                    ),
                ),
                ("mark_connected", models.BooleanField(default=False)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "connector_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("color", utilities.fields.ColorField(blank=True, max_length=6)),
                (
                    "_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.location",
                    ),
                ),
                (
                    "_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dcim.cablepath",
                    ),
                ),
                (
                    "_rack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.rack",
                    ),
                ),
                (
                    "_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.site",
                    ),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.cable",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.device",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.module",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "cooling_port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coolingoutlets",
                        to="dcim.coolingport",
                    ),
                ),
            ],
            options={
                "verbose_name": "cooling outlet",
                "verbose_name_plural": "cooling outlets",
                "ordering": ("device", "name"),
                "abstract": False,
            },
            bases=(
                netbox.models.deletion.DeleteMixin,
                models.Model,
                utilities.tracking.TrackingModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="CoolingPortTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "diameter_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_diameter",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                ("name", models.CharField(db_collation="natural_sort", max_length=64)),
                ("label", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "connector_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "maximum_flow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "heat_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.devicetype",
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.moduletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "cooling port template",
                "verbose_name_plural": "cooling port templates",
                "ordering": ("device_type", "module_type", "name"),
                "abstract": False,
            },
            bases=(
                netbox.models.deletion.DeleteMixin,
                models.Model,
                utilities.tracking.TrackingModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="CoolingOutletTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "diameter_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_diameter",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                ("name", models.CharField(db_collation="natural_sort", max_length=64)),
                ("label", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "connector_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("color", utilities.fields.ColorField(blank=True, max_length=6)),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.devicetype",
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="dcim.moduletype",
                    ),
                ),
                (
                    "cooling_port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coolingoutlet_templates",
                        to="dcim.coolingporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "cooling outlet template",
                "verbose_name_plural": "cooling outlet templates",
                "ordering": ("device_type", "module_type", "name"),
                "abstract": False,
            },
            bases=(
                netbox.models.deletion.DeleteMixin,
                models.Model,
                utilities.tracking.TrackingModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="CoolingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                (
                    "supply_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "return_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "temperature_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_supply_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "_abs_return_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("name", models.CharField(db_collation="natural_sort", max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("status", models.CharField(default="active", max_length=50)),
                (
                    "cooling_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dcim.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="users.owner",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dcim.site"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "cooling source",
                "verbose_name_plural": "cooling sources",
                "ordering": ["site", "name"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CoolingFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "flow_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "flow_rate_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_flow_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pressure_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_pressure",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=13, null=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("cable_end", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "cable_connector",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
                (
                    "cable_positions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(1024),
                            ]
                        ),
                        blank=True,
                        null=True,
                    ),
                ),
                ("mark_connected", models.BooleanField(default=False)),
                (
                    "supply_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "return_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "temperature_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "_abs_supply_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "_abs_return_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("name", models.CharField(db_collation="natural_sort", max_length=100)),
                ("status", models.CharField(default="active", max_length=50)),
                ("type", models.CharField(default="supply", max_length=50)),
                ("fluid_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cooling_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dcim.cablepath",
                    ),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dcim.cable",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="users.owner",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cooling_feeds",
                        to="dcim.rack",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cooling_feeds",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "cooling_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cooling_feeds",
                        to="dcim.coolingsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "cooling feed",
                "verbose_name_plural": "cooling feeds",
                "ordering": ["cooling_source", "name"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="coolingport",
            constraint=models.UniqueConstraint(
                fields=("device", "name"), name="dcim_coolingport_unique_device_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingoutlet",
            constraint=models.UniqueConstraint(
                fields=("device", "name"), name="dcim_coolingoutlet_unique_device_name"
            ),
        ),
        migrations.AddIndex(
            model_name="coolingporttemplate",
            index=models.Index(
                fields=["device_type", "module_type", "name"],
                name="dcim_coolin_device__0665e2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingporttemplate",
            constraint=models.UniqueConstraint(
                fields=("device_type", "name"),
                name="dcim_coolingporttemplate_unique_device_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingporttemplate",
            constraint=models.UniqueConstraint(
                fields=("module_type", "name"),
                name="dcim_coolingporttemplate_unique_module_type_name",
            ),
        ),
        migrations.AddIndex(
            model_name="coolingoutlettemplate",
            index=models.Index(
                fields=["device_type", "module_type", "name"],
                name="dcim_coolin_device__a5bf09_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingoutlettemplate",
            constraint=models.UniqueConstraint(
                fields=("device_type", "name"),
                name="dcim_coolingoutlettemplate_unique_device_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingoutlettemplate",
            constraint=models.UniqueConstraint(
                fields=("module_type", "name"),
                name="dcim_coolingoutlettemplate_unique_module_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingsource",
            constraint=models.UniqueConstraint(
                fields=("site", "name"), name="dcim_coolingsource_unique_site_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="coolingfeed",
            constraint=models.UniqueConstraint(
                fields=("cooling_source", "name"),
                name="dcim_coolingfeed_unique_cooling_source_name",
            ),
        ),
    ]
