# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0008_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
    ]
