# Generated by Django 2.2.1 on 2019-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0018_exporttemplate_add_jinja2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldchoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exporttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customfieldchoice',
            constraint=models.UniqueConstraint(fields=('field', 'value'), name='unique_field_and_value_on_customfieldchoice'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('field', 'obj_type', 'obj_id'), name='unique_custom_field_on_customfieldvalue'),
        ),
        migrations.AddConstraint(
            model_name='exporttemplate',
            constraint=models.UniqueConstraint(fields=('content_type', 'name'), name='unique_name_and_type_on_exporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='webhook',
            constraint=models.UniqueConstraint(fields=('payload_url', 'type_create', 'type_update', 'type_delete'), name='unique_webhook_type_and_payload_on_webhook'),
        ),
    ]
