# Generated by Django 2.2.4 on 2019-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0018_exporttemplate_add_jinja2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldchoice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exporttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customfieldchoice',
            constraint=models.UniqueConstraint(fields=('field', 'value'), name='customfieldchoice_field_value_key'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('field', 'obj_type', 'obj_id'), name='customfieldvalue_customfield_key'),
        ),
        migrations.AddConstraint(
            model_name='exporttemplate',
            constraint=models.UniqueConstraint(fields=('content_type', 'name'), name='exporttemplate_name_contenttype_key'),
        ),
        migrations.AddConstraint(
            model_name='webhook',
            constraint=models.UniqueConstraint(fields=('payload_url', 'type_create', 'type_update', 'type_delete'), name='webhook_webhooktype_payload_key'),
        ),
    ]
