# Generated by Django 2.2.8 on 2020-01-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0036_contenttype_filters_to_q_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontext',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
