# Generated by Django 4.0.8 on 2022-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0077_customlink_extend_text_and_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_cloneable',
            field=models.BooleanField(default=False),
        ),
    ]
