# Generated by Django 4.1.1 on 2022-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0079_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='search_weight',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
