# Generated by Django 4.1.7 on 2023-03-27 17:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0091_create_managedfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobResult',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag['IGNORECASE'],
                        message='Only alphanumeric characters and underscores are allowed.',
                        regex='^[a-z0-9_]+$',
                    ),
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag['IGNORECASE'],
                        message='No double-underscores are allowed.',
                        regex='^(?!.*__.*)',
                    ),
                ],
            ),
        ),
    ]
