# Generated by Django 4.1.9 on 2023-05-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0092_delete_jobresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='new_window',
            field=models.BooleanField(default=False),
        ),
    ]
