# Generated by Django 4.1.9 on 2023-06-22 19:33

from django.db import migrations, models
import extras.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0093_configrevision_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='object_types',
            field=models.ManyToManyField(blank=True, limit_choices_to=extras.utils.FeatureQuery('tags'), related_name='+', to='contenttypes.contenttype'),
        ),
    ]
