# Generated by Django 4.1.10 on 2023-07-18 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0097_customfield_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldchoiceset',
            name='base_choices',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customfieldchoiceset',
            name='extra_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
