# Generated by Django 4.2.7 on 2023-11-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0101_move_configrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
