# Generated by Django 5.0.1 on 2024-01-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0105_customfield_min_max_values'),
        ('core', '0011_job_report_to_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportModule',
        ),
    ]
