# Generated by Django 4.2.9 on 2024-02-05 21:37

from django.db import migrations, models
import django.db.models.deletion


def update_scripts(apps, schema_editor):
    from extras.models import ScriptModule
    ScriptModuleNew = apps.get_model('extras', 'ScriptModule')
    Script = apps.get_model('extras', 'Script')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(app_label='extras', model='script').first()

    for module in ScriptModule.objects.all():
        for script in module.get_module_scripts.keys():
            obj = Script.objects.create(
                name=script,
                module=ScriptModuleNew.objects.get(file_root=module.file_root, file_path=module.file_path),
            )

            # update all jobs associated with this module/name to point to the new script obj
            if ct:
                module.jobs.filter(name=script).update(object_type=ct, object_id=obj.id)


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0106_bookmark_user_cascade_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=79)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='extras.scriptmodule')),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='script',
            constraint=models.UniqueConstraint(fields=('name', 'module'), name='extras_script_unique_name_module'),
        ),
        migrations.RunPython(
            code=update_scripts,
            reverse_code=migrations.RunPython.noop
        ),
    ]
