# Generated by Django 4.2.9 on 2024-02-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0106_bookmark_user_cascade_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='name',
            field=models.CharField(default=None, max_length=79),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='script_module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='extras.scriptmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ('name', 'pk')},
        ),
    ]
