# Generated by Django 4.2.9 on 2024-02-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0108_script_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrule',
            name='action_parameters',
        ),
    ]
