# Generated by Django 5.0.7 on 2024-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0115_convert_dashboard_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='related_object_filter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
