# Generated by Django 5.2b1 on 2025-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_exporttemplate_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttemplate',
            name='environment_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
