# Generated by Django 5.2.4 on 2025-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0129_fix_script_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
