# Generated by Django 5.2.5 on 2025-09-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0130_alter_customfield_validation_maximum_and_more'),
        ('extras', '0132_configcontextprofile'),
    ]

    operations = [
    ]
