# Generated by Django 5.2.6 on 2025-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
