# Generated by Django 2.2.1 on 2019-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0005_change_logging'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(fields=('device', 'role', 'name'), name='unique_device_and_role_and_name'),
        ),
    ]
