# Generated by Django 2.0.8 on 2018-08-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('secrets', '0005_change_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='secret',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
