# Generated by Django 2.2.4 on 2019-08-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0005_change_logging'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(fields=('device', 'role', 'name'), name='secret_device_role_name_key'),
        ),
    ]
