# Generated by Django 2.2.8 on 2020-01-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0007_secretrole_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretrole',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
