# Generated by Django 2.0.8 on 2018-08-10 16:37
 from django.db import migrations, models
import django.db.models.deletion
 class Migration(migrations.Migration):
     dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('secrets', '0007_populate_generic_foreign_key'),
    ]
     operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ['content_type', 'object_id', 'role', 'name']},
        ),
        migrations.AlterField(
            model_name='secret',
            name='content_type',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('content_type', 'object_id', 'role', 'name')},
        ),
        migrations.RemoveField(
            model_name='secret',
            name='device',
        ),
     ]
